#############################################################################
# Configuration for the HA cluster

capi_cluster_addons_ingress_load_balancer_ip: "130.246.215.12"
zenith_sshd_service_load_balancer_ip: "130.246.83.235"

#############################################################################
# Ingress configuration

# The base domain to use for ingress resources
ingress_base_domain: "apps.staging-cape.stfc.ac.uk"

# TODO: remove this once we get tls certs for staging 
# Disable HTTPS and certificate verification everywhere to avoid certificate issues
ingress_tls_enabled: false
# Disable SSL verification for OpenStack in case it uses a custom CA
azimuth_openstack_verify_ssl: false
